{% set name = "pymust" %}
{% set version = "0.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pymust-{{ version }}.tar.gz
  sha256: 3ea134f445a70573bfcd48228d817ab73307e668c7eb3d4996a36e249f22bb08

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - numpy
    - scipy

test:
  imports:
    - pymust
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/PyMUST/
  summary: Python port of the MUST toolbox for ultrasound signal processing and generation of simulated signals
  license: LGPL-2.1
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gbernardino
